module.exports = {
  baseLength: 140,
  melody: [
    { scale: 'do', level: 1, length: 2 },
    { scale: 'do', level: 1, length: 1 },
    { scale: 're', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 2 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 're', level: 1, length: 1 },
    { scale: 're', level: 1, length: 1 },
    { scale: 'do', level: 1, length: 4 },

    { scale: 'mi', level: 1, length: 2 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 2 },
    { scale: 'do', level: 2, length: 2 },
    { scale: 'ra', level: 1, length: 2 },
    { scale: 'do', level: 2, length: 2 },
    { scale: 'so', level: 1, length: 4 },

    { scale: 'do', level: 2, length: 2 },
    { scale: 'do', level: 2, length: 2 },
    { scale: 'si', level: 1, length: 2 },
    { scale: 'so', level: 1, length: 2 },
    { scale: 'ra', level: 1, length: 1 },
    { scale: 'ra', level: 1, length: 1 },
    { scale: 'ra', level: 1, length: 1 },
    { scale: 'ra', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 4 },

    { scale: 'do', level: 1, length: 2 },
    { scale: 'do', level: 1, length: 1 },
    { scale: 're', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 2 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 're', level: 1, length: 1 },
    { scale: 're', level: 1, length: 1 },
    { scale: 'do', level: 1, length: 4 },
  ],
};