module.exports = {
  baseLength: 70,
  melody: [
    { scale: 'so', level: 1, length: 3 },
    { scale: 'so', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 3 },
    { scale: 'so', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 3 },
    { scale: 'so', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'do', level: 2, length: 1 },
    { scale: 'si', level: 1, length: 8 },

    { scale: 'fa', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 're', level: 1, length: 3 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'fa', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 're', level: 1, length: 3 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 'fa', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 're', level: 1, length: 3 },
    { scale: 'ra', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 8 },

    { scale: 'so', level: 1, length: 3 },
    { scale: 'so', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 3 },
    { scale: 'so', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 3 },
    { scale: 'so', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'do', level: 2, length: 1 },
    { scale: 'ra', level: 1, length: 4 },
    { scale: 're', level: 2, length: 3 },
    { scale: 'do', level: 2, length: 1 },

    { scale: 'si', level: 1, length: 3 },
    { scale: 'ra', level: 1, length: 1 },
    { scale: 'so', level: 1, length: 3 },
    { scale: 'fa', level: 1, length: 1 },
    { scale: 'mi', level: 1, length: 3 },
    { scale: 'mi', level: 1, length: 1 },
    { scale: 're', level: 1, length: 3 },
    { scale: 're', level: 1, length: 1 },
    { scale: 'do', level: 1, length: 4 },
    { scale: 'do', level: 2, length: 4 },
    { scale: 'do', level: 2, length: 4 },

  ],
};